# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from scooter_control/SensorHub.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import sensor_msgs.msg
import std_msgs.msg

class SensorHub(genpy.Message):
  _md5sum = "8a7ff4c96a4d7dde852a8ffd7c0319b9"
  _type = "scooter_control/SensorHub"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# Unified perception message from the sensor fusion node

std_msgs/Header header

# LiDAR data
float32[] lidar_ranges
float32 angle_min
float32 angle_increment
float32 angle_max

# Ultrasonic sensor data
float32 ultrasonic_distance

# IMU data
geometry_msgs/Vector3 imu_vector

# Raw camera frame
sensor_msgs/Image camera_frame

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: sensor_msgs/Image
# This message contains an uncompressed image
# (0, 0) is at top-left corner of image
#

Header header        # Header timestamp should be acquisition time of image
                     # Header frame_id should be optical frame of camera
                     # origin of frame should be optical center of camera
                     # +x should point to the right in the image
                     # +y should point down in the image
                     # +z should point into to plane of the image
                     # If the frame_id here and the frame_id of the CameraInfo
                     # message associated with the image conflict
                     # the behavior is undefined

uint32 height         # image height, that is, number of rows
uint32 width          # image width, that is, number of columns

# The legal values for encoding are in file src/image_encodings.cpp
# If you want to standardize a new string format, join
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.

string encoding       # Encoding of pixels -- channel meaning, ordering, size
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h

uint8 is_bigendian    # is this data bigendian?
uint32 step           # Full row length in bytes
uint8[] data          # actual matrix data, size is (step * rows)
"""
  __slots__ = ['header','lidar_ranges','angle_min','angle_increment','angle_max','ultrasonic_distance','imu_vector','camera_frame']
  _slot_types = ['std_msgs/Header','float32[]','float32','float32','float32','float32','geometry_msgs/Vector3','sensor_msgs/Image']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,lidar_ranges,angle_min,angle_increment,angle_max,ultrasonic_distance,imu_vector,camera_frame

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SensorHub, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lidar_ranges is None:
        self.lidar_ranges = []
      if self.angle_min is None:
        self.angle_min = 0.
      if self.angle_increment is None:
        self.angle_increment = 0.
      if self.angle_max is None:
        self.angle_max = 0.
      if self.ultrasonic_distance is None:
        self.ultrasonic_distance = 0.
      if self.imu_vector is None:
        self.imu_vector = geometry_msgs.msg.Vector3()
      if self.camera_frame is None:
        self.camera_frame = sensor_msgs.msg.Image()
    else:
      self.header = std_msgs.msg.Header()
      self.lidar_ranges = []
      self.angle_min = 0.
      self.angle_increment = 0.
      self.angle_max = 0.
      self.ultrasonic_distance = 0.
      self.imu_vector = geometry_msgs.msg.Vector3()
      self.camera_frame = sensor_msgs.msg.Image()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.lidar_ranges)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.lidar_ranges))
      _x = self
      buff.write(_get_struct_4f3d3I().pack(_x.angle_min, _x.angle_increment, _x.angle_max, _x.ultrasonic_distance, _x.imu_vector.x, _x.imu_vector.y, _x.imu_vector.z, _x.camera_frame.header.seq, _x.camera_frame.header.stamp.secs, _x.camera_frame.header.stamp.nsecs))
      _x = self.camera_frame.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.camera_frame.height, _x.camera_frame.width))
      _x = self.camera_frame.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.camera_frame.is_bigendian, _x.camera_frame.step))
      _x = self.camera_frame.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.imu_vector is None:
        self.imu_vector = geometry_msgs.msg.Vector3()
      if self.camera_frame is None:
        self.camera_frame = sensor_msgs.msg.Image()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.lidar_ranges = s.unpack(str[start:end])
      _x = self
      start = end
      end += 52
      (_x.angle_min, _x.angle_increment, _x.angle_max, _x.ultrasonic_distance, _x.imu_vector.x, _x.imu_vector.y, _x.imu_vector.z, _x.camera_frame.header.seq, _x.camera_frame.header.stamp.secs, _x.camera_frame.header.stamp.nsecs,) = _get_struct_4f3d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.camera_frame.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.camera_frame.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.camera_frame.height, _x.camera_frame.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.camera_frame.encoding = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.camera_frame.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.camera_frame.is_bigendian, _x.camera_frame.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.camera_frame.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.lidar_ranges)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.lidar_ranges.tostring())
      _x = self
      buff.write(_get_struct_4f3d3I().pack(_x.angle_min, _x.angle_increment, _x.angle_max, _x.ultrasonic_distance, _x.imu_vector.x, _x.imu_vector.y, _x.imu_vector.z, _x.camera_frame.header.seq, _x.camera_frame.header.stamp.secs, _x.camera_frame.header.stamp.nsecs))
      _x = self.camera_frame.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.camera_frame.height, _x.camera_frame.width))
      _x = self.camera_frame.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.camera_frame.is_bigendian, _x.camera_frame.step))
      _x = self.camera_frame.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.imu_vector is None:
        self.imu_vector = geometry_msgs.msg.Vector3()
      if self.camera_frame is None:
        self.camera_frame = sensor_msgs.msg.Image()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.lidar_ranges = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 52
      (_x.angle_min, _x.angle_increment, _x.angle_max, _x.ultrasonic_distance, _x.imu_vector.x, _x.imu_vector.y, _x.imu_vector.z, _x.camera_frame.header.seq, _x.camera_frame.header.stamp.secs, _x.camera_frame.header.stamp.nsecs,) = _get_struct_4f3d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.camera_frame.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.camera_frame.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.camera_frame.height, _x.camera_frame.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.camera_frame.encoding = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.camera_frame.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.camera_frame.is_bigendian, _x.camera_frame.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.camera_frame.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4f3d3I = None
def _get_struct_4f3d3I():
    global _struct_4f3d3I
    if _struct_4f3d3I is None:
        _struct_4f3d3I = struct.Struct("<4f3d3I")
    return _struct_4f3d3I
_struct_BI = None
def _get_struct_BI():
    global _struct_BI
    if _struct_BI is None:
        _struct_BI = struct.Struct("<BI")
    return _struct_BI
