# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from scooter_control/YoloDetection.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class YoloDetection(genpy.Message):
  _md5sum = "83c40f205e7d2dabf77dfc8fb221a703"
  _type = "scooter_control/YoloDetection"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Defines a single YOLO object detection

# Class label of the detected object
string class_label

# Confidence score of the detection
float32 confidence

# Bounding box coordinates (in pixel space)
# top-left corner
int32 x_min
int32 y_min
# bottom-right corner
int32 x_max
int32 y_max
float32 distance   # estimated distance to object in meters, -1 if unknown
"""
  __slots__ = ['class_label','confidence','x_min','y_min','x_max','y_max','distance']
  _slot_types = ['string','float32','int32','int32','int32','int32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       class_label,confidence,x_min,y_min,x_max,y_max,distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(YoloDetection, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.class_label is None:
        self.class_label = ''
      if self.confidence is None:
        self.confidence = 0.
      if self.x_min is None:
        self.x_min = 0
      if self.y_min is None:
        self.y_min = 0
      if self.x_max is None:
        self.x_max = 0
      if self.y_max is None:
        self.y_max = 0
      if self.distance is None:
        self.distance = 0.
    else:
      self.class_label = ''
      self.confidence = 0.
      self.x_min = 0
      self.y_min = 0
      self.x_max = 0
      self.y_max = 0
      self.distance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.class_label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f4if().pack(_x.confidence, _x.x_min, _x.y_min, _x.x_max, _x.y_max, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.class_label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.class_label = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.confidence, _x.x_min, _x.y_min, _x.x_max, _x.y_max, _x.distance,) = _get_struct_f4if().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.class_label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f4if().pack(_x.confidence, _x.x_min, _x.y_min, _x.x_max, _x.y_max, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.class_label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.class_label = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.confidence, _x.x_min, _x.y_min, _x.x_max, _x.y_max, _x.distance,) = _get_struct_f4if().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f4if = None
def _get_struct_f4if():
    global _struct_f4if
    if _struct_f4if is None:
        _struct_f4if = struct.Struct("<f4if")
    return _struct_f4if
