// Generated by gencpp from file scooter_control/AICommand.msg
// DO NOT EDIT!


#ifndef SCOOTER_CONTROL_MESSAGE_AICOMMAND_H
#define SCOOTER_CONTROL_MESSAGE_AICOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scooter_control
{
template <class ContainerAllocator>
struct AICommand_
{
  typedef AICommand_<ContainerAllocator> Type;

  AICommand_()
    : speed(0.0)
    , steering_angle(0.0)
    , command()  {
    }
  AICommand_(const ContainerAllocator& _alloc)
    : speed(0.0)
    , steering_angle(0.0)
    , command(_alloc)  {
  (void)_alloc;
    }



   typedef float _speed_type;
  _speed_type speed;

   typedef float _steering_angle_type;
  _steering_angle_type steering_angle;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::scooter_control::AICommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scooter_control::AICommand_<ContainerAllocator> const> ConstPtr;

}; // struct AICommand_

typedef ::scooter_control::AICommand_<std::allocator<void> > AICommand;

typedef boost::shared_ptr< ::scooter_control::AICommand > AICommandPtr;
typedef boost::shared_ptr< ::scooter_control::AICommand const> AICommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scooter_control::AICommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scooter_control::AICommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scooter_control::AICommand_<ContainerAllocator1> & lhs, const ::scooter_control::AICommand_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.steering_angle == rhs.steering_angle &&
    lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scooter_control::AICommand_<ContainerAllocator1> & lhs, const ::scooter_control::AICommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scooter_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scooter_control::AICommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scooter_control::AICommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scooter_control::AICommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scooter_control::AICommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scooter_control::AICommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scooter_control::AICommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scooter_control::AICommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0232b7d0c8d7c3cb97587aa6b1c5ccf";
  }

  static const char* value(const ::scooter_control::AICommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0232b7d0c8d7c3cULL;
  static const uint64_t static_value2 = 0xb97587aa6b1c5ccfULL;
};

template<class ContainerAllocator>
struct DataType< ::scooter_control::AICommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scooter_control/AICommand";
  }

  static const char* value(const ::scooter_control::AICommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scooter_control::AICommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Defines the final command sent to the motor controller\n"
"# It includes a speed value and a steering angle.\n"
"\n"
"# Speed in meters/second.\n"
"# Positive for forward, 0 for stop.\n"
"float32 speed\n"
"\n"
"# Steering angle in radians.\n"
"# 0 is straight, positive is left, negative is right.\n"
"float32 steering_angle\n"
"\n"
"# A command string for high-level instructions or status\n"
"# e.g., \"STOP\", \"CRUISE\", \"AVOID_LEFT\"\n"
"string command\n"
;
  }

  static const char* value(const ::scooter_control::AICommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scooter_control::AICommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.steering_angle);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AICommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scooter_control::AICommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scooter_control::AICommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "steering_angle: ";
    Printer<float>::stream(s, indent + "  ", v.steering_angle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCOOTER_CONTROL_MESSAGE_AICOMMAND_H
