// Generated by gencpp from file scooter_control/SensorHub.msg
// DO NOT EDIT!


#ifndef SCOOTER_CONTROL_MESSAGE_SENSORHUB_H
#define SCOOTER_CONTROL_MESSAGE_SENSORHUB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <sensor_msgs/Image.h>

namespace scooter_control
{
template <class ContainerAllocator>
struct SensorHub_
{
  typedef SensorHub_<ContainerAllocator> Type;

  SensorHub_()
    : header()
    , lidar_ranges()
    , angle_min(0.0)
    , angle_increment(0.0)
    , angle_max(0.0)
    , ultrasonic_distance(0.0)
    , imu_vector()
    , camera_frame()  {
    }
  SensorHub_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lidar_ranges(_alloc)
    , angle_min(0.0)
    , angle_increment(0.0)
    , angle_max(0.0)
    , ultrasonic_distance(0.0)
    , imu_vector(_alloc)
    , camera_frame(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _lidar_ranges_type;
  _lidar_ranges_type lidar_ranges;

   typedef float _angle_min_type;
  _angle_min_type angle_min;

   typedef float _angle_increment_type;
  _angle_increment_type angle_increment;

   typedef float _angle_max_type;
  _angle_max_type angle_max;

   typedef float _ultrasonic_distance_type;
  _ultrasonic_distance_type ultrasonic_distance;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _imu_vector_type;
  _imu_vector_type imu_vector;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _camera_frame_type;
  _camera_frame_type camera_frame;





  typedef boost::shared_ptr< ::scooter_control::SensorHub_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scooter_control::SensorHub_<ContainerAllocator> const> ConstPtr;

}; // struct SensorHub_

typedef ::scooter_control::SensorHub_<std::allocator<void> > SensorHub;

typedef boost::shared_ptr< ::scooter_control::SensorHub > SensorHubPtr;
typedef boost::shared_ptr< ::scooter_control::SensorHub const> SensorHubConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scooter_control::SensorHub_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scooter_control::SensorHub_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scooter_control::SensorHub_<ContainerAllocator1> & lhs, const ::scooter_control::SensorHub_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lidar_ranges == rhs.lidar_ranges &&
    lhs.angle_min == rhs.angle_min &&
    lhs.angle_increment == rhs.angle_increment &&
    lhs.angle_max == rhs.angle_max &&
    lhs.ultrasonic_distance == rhs.ultrasonic_distance &&
    lhs.imu_vector == rhs.imu_vector &&
    lhs.camera_frame == rhs.camera_frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scooter_control::SensorHub_<ContainerAllocator1> & lhs, const ::scooter_control::SensorHub_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scooter_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scooter_control::SensorHub_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scooter_control::SensorHub_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scooter_control::SensorHub_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scooter_control::SensorHub_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scooter_control::SensorHub_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scooter_control::SensorHub_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scooter_control::SensorHub_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a7ff4c96a4d7dde852a8ffd7c0319b9";
  }

  static const char* value(const ::scooter_control::SensorHub_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a7ff4c96a4d7ddeULL;
  static const uint64_t static_value2 = 0x852a8ffd7c0319b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::scooter_control::SensorHub_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scooter_control/SensorHub";
  }

  static const char* value(const ::scooter_control::SensorHub_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scooter_control::SensorHub_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Unified perception message from the sensor fusion node\n"
"\n"
"std_msgs/Header header\n"
"\n"
"# LiDAR data\n"
"float32[] lidar_ranges\n"
"float32 angle_min\n"
"float32 angle_increment\n"
"float32 angle_max\n"
"\n"
"# Ultrasonic sensor data\n"
"float32 ultrasonic_distance\n"
"\n"
"# IMU data\n"
"geometry_msgs/Vector3 imu_vector\n"
"\n"
"# Raw camera frame\n"
"sensor_msgs/Image camera_frame\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::scooter_control::SensorHub_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scooter_control::SensorHub_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lidar_ranges);
      stream.next(m.angle_min);
      stream.next(m.angle_increment);
      stream.next(m.angle_max);
      stream.next(m.ultrasonic_distance);
      stream.next(m.imu_vector);
      stream.next(m.camera_frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorHub_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scooter_control::SensorHub_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scooter_control::SensorHub_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lidar_ranges: ";
    if (v.lidar_ranges.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.lidar_ranges.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.lidar_ranges[i]);
    }
    if (v.lidar_ranges.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angle_min: ";
    Printer<float>::stream(s, indent + "  ", v.angle_min);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angle_increment: ";
    Printer<float>::stream(s, indent + "  ", v.angle_increment);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angle_max: ";
    Printer<float>::stream(s, indent + "  ", v.angle_max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ultrasonic_distance: ";
    Printer<float>::stream(s, indent + "  ", v.ultrasonic_distance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_vector: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.imu_vector);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "camera_frame: ";
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.camera_frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCOOTER_CONTROL_MESSAGE_SENSORHUB_H
