// Generated by gencpp from file scooter_control/YoloDetection.msg
// DO NOT EDIT!


#ifndef SCOOTER_CONTROL_MESSAGE_YOLODETECTION_H
#define SCOOTER_CONTROL_MESSAGE_YOLODETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scooter_control
{
template <class ContainerAllocator>
struct YoloDetection_
{
  typedef YoloDetection_<ContainerAllocator> Type;

  YoloDetection_()
    : class_label()
    , confidence(0.0)
    , x_min(0)
    , y_min(0)
    , x_max(0)
    , y_max(0)
    , distance(0.0)  {
    }
  YoloDetection_(const ContainerAllocator& _alloc)
    : class_label(_alloc)
    , confidence(0.0)
    , x_min(0)
    , y_min(0)
    , x_max(0)
    , y_max(0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_label_type;
  _class_label_type class_label;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef int32_t _x_min_type;
  _x_min_type x_min;

   typedef int32_t _y_min_type;
  _y_min_type y_min;

   typedef int32_t _x_max_type;
  _x_max_type x_max;

   typedef int32_t _y_max_type;
  _y_max_type y_max;

   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::scooter_control::YoloDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scooter_control::YoloDetection_<ContainerAllocator> const> ConstPtr;

}; // struct YoloDetection_

typedef ::scooter_control::YoloDetection_<std::allocator<void> > YoloDetection;

typedef boost::shared_ptr< ::scooter_control::YoloDetection > YoloDetectionPtr;
typedef boost::shared_ptr< ::scooter_control::YoloDetection const> YoloDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scooter_control::YoloDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scooter_control::YoloDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scooter_control::YoloDetection_<ContainerAllocator1> & lhs, const ::scooter_control::YoloDetection_<ContainerAllocator2> & rhs)
{
  return lhs.class_label == rhs.class_label &&
    lhs.confidence == rhs.confidence &&
    lhs.x_min == rhs.x_min &&
    lhs.y_min == rhs.y_min &&
    lhs.x_max == rhs.x_max &&
    lhs.y_max == rhs.y_max &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scooter_control::YoloDetection_<ContainerAllocator1> & lhs, const ::scooter_control::YoloDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scooter_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scooter_control::YoloDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scooter_control::YoloDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scooter_control::YoloDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scooter_control::YoloDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scooter_control::YoloDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scooter_control::YoloDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scooter_control::YoloDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83c40f205e7d2dabf77dfc8fb221a703";
  }

  static const char* value(const ::scooter_control::YoloDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83c40f205e7d2dabULL;
  static const uint64_t static_value2 = 0xf77dfc8fb221a703ULL;
};

template<class ContainerAllocator>
struct DataType< ::scooter_control::YoloDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scooter_control/YoloDetection";
  }

  static const char* value(const ::scooter_control::YoloDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scooter_control::YoloDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Defines a single YOLO object detection\n"
"\n"
"# Class label of the detected object\n"
"string class_label\n"
"\n"
"# Confidence score of the detection\n"
"float32 confidence\n"
"\n"
"# Bounding box coordinates (in pixel space)\n"
"# top-left corner\n"
"int32 x_min\n"
"int32 y_min\n"
"# bottom-right corner\n"
"int32 x_max\n"
"int32 y_max\n"
"float32 distance   # estimated distance to object in meters, -1 if unknown\n"
;
  }

  static const char* value(const ::scooter_control::YoloDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scooter_control::YoloDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.class_label);
      stream.next(m.confidence);
      stream.next(m.x_min);
      stream.next(m.y_min);
      stream.next(m.x_max);
      stream.next(m.y_max);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scooter_control::YoloDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scooter_control::YoloDetection_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "class_label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_label);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_min: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x_min);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_min: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y_min);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_max: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x_max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_max: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y_max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCOOTER_CONTROL_MESSAGE_YOLODETECTION_H
