// Generated by gencpp from file scooter_control/YoloDetectionArray.msg
// DO NOT EDIT!


#ifndef SCOOTER_CONTROL_MESSAGE_YOLODETECTIONARRAY_H
#define SCOOTER_CONTROL_MESSAGE_YOLODETECTIONARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <scooter_control/YoloDetection.h>

namespace scooter_control
{
template <class ContainerAllocator>
struct YoloDetectionArray_
{
  typedef YoloDetectionArray_<ContainerAllocator> Type;

  YoloDetectionArray_()
    : header()
    , detections()
    , source_model()  {
    }
  YoloDetectionArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)
    , source_model(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::scooter_control::YoloDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::scooter_control::YoloDetection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_model_type;
  _source_model_type source_model;





  typedef boost::shared_ptr< ::scooter_control::YoloDetectionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scooter_control::YoloDetectionArray_<ContainerAllocator> const> ConstPtr;

}; // struct YoloDetectionArray_

typedef ::scooter_control::YoloDetectionArray_<std::allocator<void> > YoloDetectionArray;

typedef boost::shared_ptr< ::scooter_control::YoloDetectionArray > YoloDetectionArrayPtr;
typedef boost::shared_ptr< ::scooter_control::YoloDetectionArray const> YoloDetectionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scooter_control::YoloDetectionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scooter_control::YoloDetectionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scooter_control::YoloDetectionArray_<ContainerAllocator1> & lhs, const ::scooter_control::YoloDetectionArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections &&
    lhs.source_model == rhs.source_model;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scooter_control::YoloDetectionArray_<ContainerAllocator1> & lhs, const ::scooter_control::YoloDetectionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scooter_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scooter_control::YoloDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scooter_control::YoloDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scooter_control::YoloDetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scooter_control::YoloDetectionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scooter_control::YoloDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scooter_control::YoloDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scooter_control::YoloDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "478a9916436565eb349ccaef92e54ba5";
  }

  static const char* value(const ::scooter_control::YoloDetectionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x478a9916436565ebULL;
  static const uint64_t static_value2 = 0x349ccaef92e54ba5ULL;
};

template<class ContainerAllocator>
struct DataType< ::scooter_control::YoloDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scooter_control/YoloDetectionArray";
  }

  static const char* value(const ::scooter_control::YoloDetectionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scooter_control::YoloDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# An array of YOLO detections from the dual_yolo_node\n"
"\n"
"std_msgs/Header header\n"
"\n"
"# Array of individual detections\n"
"YoloDetection[] detections\n"
"\n"
"# Source of the detection (e.g., \"yolov8n\", \"yolov8s\", \"fused\")\n"
"string source_model\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: scooter_control/YoloDetection\n"
"# Defines a single YOLO object detection\n"
"\n"
"# Class label of the detected object\n"
"string class_label\n"
"\n"
"# Confidence score of the detection\n"
"float32 confidence\n"
"\n"
"# Bounding box coordinates (in pixel space)\n"
"# top-left corner\n"
"int32 x_min\n"
"int32 y_min\n"
"# bottom-right corner\n"
"int32 x_max\n"
"int32 y_max\n"
"float32 distance   # estimated distance to object in meters, -1 if unknown\n"
;
  }

  static const char* value(const ::scooter_control::YoloDetectionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scooter_control::YoloDetectionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
      stream.next(m.source_model);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloDetectionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scooter_control::YoloDetectionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scooter_control::YoloDetectionArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detections: ";
    if (v.detections.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::scooter_control::YoloDetection_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.detections[i]);
    }
    if (v.detections.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "source_model: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source_model);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCOOTER_CONTROL_MESSAGE_YOLODETECTIONARRAY_H
