// Generated by gencpp from file yolo_tensorrt/YoloDetection.msg
// DO NOT EDIT!


#ifndef YOLO_TENSORRT_MESSAGE_YOLODETECTION_H
#define YOLO_TENSORRT_MESSAGE_YOLODETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo_tensorrt
{
template <class ContainerAllocator>
struct YoloDetection_
{
  typedef YoloDetection_<ContainerAllocator> Type;

  YoloDetection_()
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , score(0.0)
    , class_id(0)
    , class_name()  {
    }
  YoloDetection_(const ContainerAllocator& _alloc)
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , score(0.0)
    , class_id(0)
    , class_name(_alloc)  {
  (void)_alloc;
    }



   typedef float _x1_type;
  _x1_type x1;

   typedef float _y1_type;
  _y1_type y1;

   typedef float _x2_type;
  _x2_type x2;

   typedef float _y2_type;
  _y2_type y2;

   typedef float _score_type;
  _score_type score;

   typedef int32_t _class_id_type;
  _class_id_type class_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;





  typedef boost::shared_ptr< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> const> ConstPtr;

}; // struct YoloDetection_

typedef ::yolo_tensorrt::YoloDetection_<std::allocator<void> > YoloDetection;

typedef boost::shared_ptr< ::yolo_tensorrt::YoloDetection > YoloDetectionPtr;
typedef boost::shared_ptr< ::yolo_tensorrt::YoloDetection const> YoloDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_tensorrt::YoloDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_tensorrt::YoloDetection_<ContainerAllocator1> & lhs, const ::yolo_tensorrt::YoloDetection_<ContainerAllocator2> & rhs)
{
  return lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1 &&
    lhs.x2 == rhs.x2 &&
    lhs.y2 == rhs.y2 &&
    lhs.score == rhs.score &&
    lhs.class_id == rhs.class_id &&
    lhs.class_name == rhs.class_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_tensorrt::YoloDetection_<ContainerAllocator1> & lhs, const ::yolo_tensorrt::YoloDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_tensorrt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbc1212069278b57502e5887e3923efe";
  }

  static const char* value(const ::yolo_tensorrt::YoloDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdbc1212069278b57ULL;
  static const uint64_t static_value2 = 0x502e5887e3923efeULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_tensorrt/YoloDetection";
  }

  static const char* value(const ::yolo_tensorrt::YoloDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x1\n"
"float32 y1\n"
"float32 x2\n"
"float32 y2\n"
"float32 score\n"
"int32 class_id\n"
"string class_name\n"
;
  }

  static const char* value(const ::yolo_tensorrt::YoloDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
      stream.next(m.score);
      stream.next(m.class_id);
      stream.next(m.class_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_tensorrt::YoloDetection_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x1: ";
    Printer<float>::stream(s, indent + "  ", v.x1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y1: ";
    Printer<float>::stream(s, indent + "  ", v.y1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x2: ";
    Printer<float>::stream(s, indent + "  ", v.x2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y2: ";
    Printer<float>::stream(s, indent + "  ", v.y2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "class_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.class_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_TENSORRT_MESSAGE_YOLODETECTION_H
