// Generated by gencpp from file yolo_tensorrt/YoloDetectionArray.msg
// DO NOT EDIT!


#ifndef YOLO_TENSORRT_MESSAGE_YOLODETECTIONARRAY_H
#define YOLO_TENSORRT_MESSAGE_YOLODETECTIONARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <yolo_tensorrt/YoloDetection.h>

namespace yolo_tensorrt
{
template <class ContainerAllocator>
struct YoloDetectionArray_
{
  typedef YoloDetectionArray_<ContainerAllocator> Type;

  YoloDetectionArray_()
    : header()
    , detections()  {
    }
  YoloDetectionArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> const> ConstPtr;

}; // struct YoloDetectionArray_

typedef ::yolo_tensorrt::YoloDetectionArray_<std::allocator<void> > YoloDetectionArray;

typedef boost::shared_ptr< ::yolo_tensorrt::YoloDetectionArray > YoloDetectionArrayPtr;
typedef boost::shared_ptr< ::yolo_tensorrt::YoloDetectionArray const> YoloDetectionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator1> & lhs, const ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator1> & lhs, const ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_tensorrt

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d47333e1297da1188ba7dfb186157b6";
  }

  static const char* value(const ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d47333e1297da11ULL;
  static const uint64_t static_value2 = 0x88ba7dfb186157b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_tensorrt/YoloDetectionArray";
  }

  static const char* value(const ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"YoloDetection[] detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: yolo_tensorrt/YoloDetection\n"
"float32 x1\n"
"float32 y1\n"
"float32 x2\n"
"float32 y2\n"
"float32 score\n"
"int32 class_id\n"
"string class_name\n"
;
  }

  static const char* value(const ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloDetectionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_tensorrt::YoloDetectionArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detections: ";
    if (v.detections.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::yolo_tensorrt::YoloDetection_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.detections[i]);
    }
    if (v.detections.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_TENSORRT_MESSAGE_YOLODETECTIONARRAY_H
